version: '3'

services:
  postgres:
    image: postgres:15
    container_name: studio_postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # strapi:
  #   build: ./backend
  #   container_name: studio_strapi
  #   environment:
  #     DATABASE_CLIENT: postgres
  #     DATABASE_NAME: strapi
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_USERNAME: strapi
  #     DATABASE_PASSWORD: strapi
  #     NODE_ENV: development
  #   ports:
  #     - "1337:1337"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./backend:/app

volumes:
  pgdata:
